# Generated by Django 4.2.28 on 2026-03-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fine_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
